- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create Deployment
      k8s:
        state: present
        resource_definition: |
            "kind": "DeploymentConfig",
            "apiVersion": "v1",
            "metadata": {
                "name": "php-laravel",
                "annotations": {
                    "description": "Defines how to deploy the application server",
                    "template.alpha.openshift.io/wait-for-ready": "true"
                }
            },
            "spec": {
                "strategy": {
                    "type": "Rolling",
                    "rollingParams":{
                        "updatePeriodSeconds": 1, 
                        "intervalSeconds": 1,
                        "timeoutSeconds": 120, 
                        "maxSurge": "20%", 
                        "maxUnavailable": "50%", 
                        "pre": {
                            "execNewPod": {
                                "command": [
                                    "./migrate-database.sh"
                                ],
                                "containerName": "php-laravel"
                            },
                            "failurePolicy": "Retry"
                        } 
                    }    
                },
                
                "triggers": [
                    {
                        "imageChangeParams": {
                            "automatic": true,
                            "containerNames": [
                                "php-laravel"
                            ],
                            "from": {
                                "kind": "ImageStreamTag",
                                "name": "php-laravel:latest"
                            }
                        },
                        "type": "ImageChange"
                    },
                    {
                        "type": "ConfigChange"
                    }
                ],
                "replicas": 1,
                "selector": {
                    "name": "php-laravel"
                },
                "template": {
                    "metadata": {                        
                        "name": "php-laravel",
                        "labels": {
                            "name": "php-laravel"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "name": "php-laravel",
                                "image": "",
                                "ports": [
                                    {
                                        "containerPort": 8080
                                    }
                                ],
                                "readinessProbe": {
                                    "httpGet": {
                                        "path": "/health.php",
                                        "port": 8080
                                    },
                                    "initialDelaySeconds": 3,
                                    "timeoutSeconds": 3
                                },
                                "livenessProbe": {
                                    "httpGet": {
                                        "path": "/",
                                        "port": 8080
                                    },
                                    "initialDelaySeconds": 30,
                                    "timeoutSeconds": 3
                                },
                                "env": [
                                    {
                                        "name": "ROUTER_SHARD",
                                        "value": "44fs"
                                    },
                                    {
                                        "name": "DB_CONNECTION",
                                        "value": "sqlite"
                                    },
                                    {
                                        "name": "APP_KEY",
                                        "value": "abcgdftyuj7wooopjkuyehatyehdklxouyto977"
                                    },
                                    {
                                        "name": "APP_ENV",
                                        "value": "dev"
                                    },
                                    {
                                        "name": "APP_DEBUG",
                                        "value": 1
                                    },
                                    {
                                        "name": "OPCACHE_REVALIDATE_FREQ",
                                        "value": 0
                                    }
                                ],
                                "resources": {
                                    "limits": {
                                        "memory": 512Mi
                                    }
                                }
                            }
                        ]
                    }
                }

            }
        
      register: deployment 

    - name: Get the Deployment
      k8s_info:
        kind: Deployment
        namespace: pipeline-tutorial
      register: laravel_deployments_list
    - name: Log Deployment Details
      debug:
        msg: "{{ item | json_query('metadata.name') }}"
      loop: '{{funstuff_deployments_list.resources}}'
      loop_control:
        label: "Deployment (Namespace: {{item | json_query('metadata.namespace')}},Replicas:{{ item | json_query('spec.replicas')}})"
