- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create Image ImageStream 
      k8s: 
        state: present 
        resource_definition: |
          kind: ImageStream
          apiVersion: v1
          metadata:
            name: "laravel_devel"
            annotations:
              description: Keeps track of changes in the application image

    - name: Create Build Config
      k8s: 
        state: present 
        resource_definition: |
          kind: BuildConfig
          apiVersion: v1
          metadata:
            name: "laravel_devel"
            annotations:
              description: Defines how to build the application
              template.alpha.openshift.io/wait-for-ready: 'true'
          spec:
            source:
              contextDir: /var/www/html
              type: Git
              git:
                uri: https://github.com/lutfi-ingram/laravelJenkins.git
                ref: development
            strategy:
              type: Source
              sourceStrategy:
                from:
                  kind: ImageStreamTag
                  namespace: "pipeline-tutorial"
                  name: php:7.4-ubi8
                env:
                - name: COMPOSER_MIRROR
                  value: "somewhere"
            output:
              to:
                kind: ImageStreamTag
                name: "laravel_devel:latest"
            triggers:
            - type: ImageChange
            - type: ConfigChange
            - github:
                secret: lijuow8uh883hjhkgu8jklamcjduwiplkhtjnuki
              type: GitHub

    - name: Get the Deployment
      k8s_info:
        kind: Deployment
        namespace: pipeline-tutorial
      register: laravel_deployments_list
    - name: Log Deployment Details
      debug:
        msg: "{{ item | json_query('metadata.name') }}"
      loop: '{{funstuff_deployments_list.resources}}'
      loop_control:
        label: "Deployment (Namespace: {{item | json_query('metadata.namespace')}},Replicas:{{ item | json_query('spec.replicas')}})"
