---
- name: Deployment Config 
  hosts: localhost
  connection: local
  collections:
    - community.kubernetes

  vars:
    namespace: "jenkins-operatorhub"
    app_name: "php-test"
    app_domain: ""
    
  tasks:
    - name: Create a namespace if not exists
      k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present    
    
    - name: Create a new Route
      k8s:
        state: present
        namespace: "{{ namespace }}"
        resource_definition: |
          kind: Route
          apiVersion: v1
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ app_domain }}"
            to:
              kind: Service
              name: "{{ app_name }}"