---
- name: Deployment Config 
  hosts: localhost
  connection: local
  collections:
    - community.kubernetes

  vars:
    namespace: "jenkins-operatorhub"
    app_name: "php-test"
    
  tasks:
    - name: Create a namespace if not exists
      k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present    
    
    - name: Create a new Service Port 8080
      k8s:
        state: present
        namespace: "{{ namespace }}"
        resource_definition: |
          kind: Service
          apiVersion: v1
          metadata:
            name: "{{ app_name }}"
            annotations:
              description: Exposes and load balances the application pods
          spec:
            ports:
            - name: web
              port: 8080
              targetPort: 8080
            selector:
              name: "{{ app_name }}"